image: srcoder/development-php:php71-fpm
definitions:
  caches:
    vendor: vendor
pipelines:
  default:
    - step:
        name: Testing suite
        caches:
          - composer
          - vendor
        script:
          - make test
          - make codecov
          - make clean

    - step:
        name: Application test
        caches:
          - vendor
        script:
          - make application-test
          - make clean

    - step:
        name: Push to GitHub
        script:
          - git remote add github $GITHUB_REMOTE
          - git push github master --tags

  tags:
    '*':
      - step:
          name: Distribute the program
          caches:
            - composer
          script:
            - make distribution

      - step:
          name: Push tags to Github
          script:
            - git remote add github $GITHUB_REMOTE
            - git push github --tags

  custom:
    Distribution:
      - step:
          name: Distribute the program
          caches:
            - composer
          script:
            - export BITBUCKET_TAG=$(git tag | tail -n -1)
            - make distribution
