image: srcoder/development-php:php71-fpm
definitions:
  caches:
    vendor: vendor
pipelines:
  default:
    - step:
        name: Composer validation
        script:
          - composer self-update
          - composer check-platform-reqs
          - composer validate --strict --no-interaction
        artifacts:
          - ./*

    - step:
        name: Testing suite
        caches:
          - composer
          - vendor
        script:
          - composer self-update
          - composer install --dev --prefer-dist --no-scripts --no-progress --optimize-autoloader --no-interaction -vvv
          - composer show
          - composer exec -v grumphp run

    - step:
        name: Push to GitHub
        script:
          - git remote add github $GITHUB_REMOTE
          - git push github --all
