image: srcoder/development-php:php71-fpm
definitions:
  caches:
    vendor: vendor
pipelines:
  default:
    - step:
        name: Composer validation
        caches:
          - composer
        script:
          - composer self-update
          - composer check-platform-reqs
          - composer validate --strict --no-interaction

    - step:
        name: Testing suite
        caches:
          - composer
          - vendor
        script:
          - composer install --dev --prefer-dist --no-scripts --no-progress --optimize-autoloader --no-interaction -vvv
          - composer show
          - composer exec -v grumphp run
          - composer exec -v phpunit -- --log-junit ./test-reports/junit.xml

  branches:
    master:
      - step:
          name: Push to GitHub
          script:
            - git remote add github $GITHUB_REMOTE
            - git push github master --tags

  tags:
    '*':
      - step:
          name: Push tags to Github
          script:
            - git remote add github $GITHUB_REMOTE
            - git push github --tags

      - step:
          name: Build artifacts
          caches:
            - composer
          script:
            - make dist/zc.phar
            - cp dist/zc.phar "dist/zc-${BITBUCKET_TAG}.phar"
            - curl -X POST --user "${BUILD_AUTH}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"dist/zc-${BITBUCKET_TAG}.phar"
            - curl -X POST --user "${BUILD_AUTH}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"dist/zc.phar"
